# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            dockerfile: Dockerfile
            args:
                WWWGROUP: 'www-data'
        image: ucs-app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: 'www-data'
        volumes:
            - '.:/var/www/html'